services:
  # Next.js SEA-Bridge App
  sea-bridge-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      # Override specific values for container environment
      - NODE_ENV=production
      - OLLAMA_ENDPOINT=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - sea-bridge-network
    restart: unless-stopped

  # Ollama SEA-LION Service
  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    # Enable GPU access in Compose (non-Swarm)
    gpus: all
    networks:
      - sea-bridge-network
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  sea-bridge-network:
    driver: bridge
